# Generated by Django 4.0.3 on 2022-04-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_alter_livro_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='co_autor',
        ),
    ]
